### ISSUE TITLE
Discord link doesn't work

### ISSUE THREAD

**Issue by duckfromdiscord** [TheLastZombie/upptime#1438]
I can't find a repo for your site so I'll post this here: your Discord link brings me to Discord but doesn't do anything.

**Comment by duckfromdiscord** [comment]
No, none of them work. I suspect it's because it only works on someone you have friended/if it's yourself.

**Comment by TheLastZombie** [comment]
Oh yeah, that could be it.

Well, in any case, I just replaced it with my username now. Thanks again for the heads-up!

**Comment by closerhan** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
redpanda321, @SpawnID0000, @spaydar, @ukexim13, @domsteil, @timxor, @hanigamal, @Steffi3rd, @BigsteppA1, @timorthi, @BruceWangyq, @regohiro, @brunobrise, @h1nk, @jdori, @nemani, @mickume, @raymondjacobson, @BelkacemB, @forgondolin, @etsploit, @unboundable-bound-soul, @Elvin1993, @afd998, @SamFrox, @ki412412, @georgelemon, @MordechaiHadad, @ghalestrilo, @willemaster, @Sandalf, @asharksfishbowl, @dkazenoff, @molotovbliss, @siredwardspike, @aljo242, @tim77, @bling666-huang, @sruud, @giacomogagliano, @wuyongyi, @Franceshe, @akarls, @DerTiedemann, @sbagency, @jonaylor89, @fransixles, @samid737, @terranmoccasin, @jayay98

**Comment by closerhan** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
lionsera, @ralphMevision, @ghosthamlet, @Tgemayel, @philkunz, @suin, @gingram68, @HolmesDomain, @bitrocks, @drewroberts, @snaveint, @baakeydow, @yakubenko, @icemusike, @AdrBender, @shoaibahmed, @truonglvx, @dnekkalapu, @sunbonilla, @PetteriPertola, @famasoon, @vir2alexport, @toremielck, @nivonova, @Avi845, @umaar, @chard0707, @atyenoria, @imyourm8, @figla12, @ZCwon, @wilsonglasser, @PurDrew2, @jackfrost373, @HODLxvg, @klpanda, @awareim, @domhaas, @jmr-9419, @hkn1979, @tonzer360, @dwichers, @nyango, @vashshawn, @dark-mb1, @matthpl, @grantgrip, @Diegovictorbr, @naveen09, @muktarpat

**Comment by risangpinto** [comment]
[![Banner](https://i.ytimg.com/vi/0jk5fGH0MYE/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
